// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  await `Firebase`.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6sUfq0SD-AMaUWfJdblfyeJdP3Q1gtpQ',
    appId: '1:932871580288:web:69288902420a3b49ccd465',
    messagingSenderId: '932871580288',
    projectId: 'catdiff-9db92',
    authDomain: 'catdiff-9db92.firebaseapp.com',
    storageBucket: 'catdiff-9db92.firebasestorage.app',
    measurementId: 'G-KSN0W6YB4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVBgGw9m8UfuoBm-IYmvP8oScRAqMVEOU',
    appId: '1:932871580288:android:62ee37e962d04eb7ccd465',
    messagingSenderId: '932871580288',
    projectId: 'catdiff-9db92',
    storageBucket: 'catdiff-9db92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKk4XYlkuUbfeUPjayZpwgi8kCxSVBUa4',
    appId: '1:932871580288:ios:a49b6fe859905068ccd465',
    messagingSenderId: '932871580288',
    projectId: 'catdiff-9db92',
    storageBucket: 'catdiff-9db92.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKk4XYlkuUbfeUPjayZpwgi8kCxSVBUa4',
    appId: '1:932871580288:ios:a49b6fe859905068ccd465',
    messagingSenderId: '932871580288',
    projectId: 'catdiff-9db92',
    storageBucket: 'catdiff-9db92.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6sUfq0SD-AMaUWfJdblfyeJdP3Q1gtpQ',
    appId: '1:932871580288:web:017ae008160e7169ccd465',
    messagingSenderId: '932871580288',
    projectId: 'catdiff-9db92',
    authDomain: 'catdiff-9db92.firebaseapp.com',
    storageBucket: 'catdiff-9db92.firebasestorage.app',
    measurementId: 'G-NG95LQVZST',
  );

}